version: '3.5'
services:
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static
    ports:
      - '9000:80'
    depends_on:
      - django
  django:
    build: ./django
    container_name: django
    expose:
      - '8001'
    volumes:
      - ./src:/code
    command: uwsgi --socket :8001 --module mysite.wsgi
    depends_on:
      - db
  jupyter:
    build: ./jupyter
    container_name: jupyter
    # ports:
    #   - "9001:8888"
    expose:
      - '8888'
    volumes:
      - ./jupyter:/notebook
    depends_on:
      - db
  db:
    image: postgres:11.15
    container_name: db
    volumes:
      - ./db/dbdata:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db-gui:
    ##### pgweb #####
    # image: sosedoff/pgweb:0.11.11
    # # environment:
    # #   DATABASE_URL: postgres://<user>:<pass>@db:5432/<DBname>?sslmode=disable
    # # ports:
    # #   - "9002:8081"
    # expose:
    #   - '8081'
    ##### pgAdmin #####
    image: dpage/pgadmin4:6.8
    environment:
      PGADMIN_DEFAULT_EMAIL: x@gmail.com
      PGADMIN_DEFAULT_PASSWORD: x
    expose:
      - '80'
    ##### 共通設定 #####
    container_name: db-gui
    depends_on:
      - db